name: build
on:
  push:
  schedule:
    - cron: '0 1 * * 6' # weekly cron schedule
jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Download repository
        uses: actions/checkout@v3

      # https://github.com/actions/setup-java
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18

      - name: Test with Maven
        run: mvn test
